obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.22, 0.22], [0.22, -0.22], [-0.22, -0.22], [-0.22, 0.22]]

inflation_radius: 0.05
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: true, observation_keep_time: 0.0, expected_update_rate: 0}
#range_sensor_layer:
#  topics: ["/ultrasound0", "/ultrasound3", "/ultrasound4"]
#  no_readings_timeout: 0.0
#  clear_threshold: 0.2
#  mark_threshold: 0.8
#  clear_on_max_reading: true
